### ISSUE TITLE
smoke_test_frames fails (x86_64-linux-gnu)

### ISSUE THREAD

**Issue by emixa-d** [rust-lang/backtrace-rs#484] opened 2022-09-25 11:02 UTC
```
starting phase `check'
Running .guix-tests/accuracy

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

Running .guix-tests/backtrace-embedded-tests

running 1 test
test capture::tests::test_frame_conversion ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

Running .guix-tests/concurrent-panics

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

Running .guix-tests/long_fn_name

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

Running .guix-tests/skip_inner_frames

running 2 tests
test backtrace_new_unresolved_should_start_with_call_site_trace ... ok
test backtrace_new_should_start_with_call_site_trace ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

Running .guix-tests/smoke

running 3 tests
test sp_smoke_test ... ok
test many_threads ... ok
test smoke_test_frames ... FAILED

failures:

---- smoke_test_frames stdout ----
symbol  ip:0x55555555b2fe address:0x55555555b2d0 name:smoke::smoke_test_frames::frame_4::h8d7ba242673ec73c file:/tmp/guix-build-rust-backtrace-0.3.66.drv-0/backtrace-0.3.66/tests/smoke.rs lineno:15 colno:9 
thread 'smoke_test_frames' panicked at 'assertion failed: resolved > 0', tests/smoke.rs:144:9
stack backtrace:
   0:     0x7ffff7e4795b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h190bc4e71a974fd5
   1:     0x7ffff7ea2cfc - core::fmt::write::h5ab597cdd0c00db2
   2:     0x7ffff7e00701 - <unknown>
   3:     0x7ffff7e23c6e - <unknown>
   4:     0x7ffff7e23952 - std::panicking::default_hook::hcffd5d909668cc52
   5:     0x7ffff7e242ae - std::panicking::rust_panic_with_hook::h67db5ff340e389bf
   6:     0x7ffff7e48239 - <unknown>
   7:     0x7ffff7e47a74 - <unknown>
   8:     0x7ffff7e23db2 - rust_begin_unwind
   9:     0x7ffff7df5ff3 - core::panicking::panic_fmt::h4b9cfd185dab4fab
  10:     0x7ffff7df5ebd - core::panicking::panic::hf302ee3c85d06830
  11:     0x55555555b8c9 - smoke::smoke_test_frames::assert_frame::hb4f2858dcefbfaa6
                               at /tmp/guix-build-rust-backtrace-0.3.66.drv-0/backtrace-0.3.66/tests/smoke.rs:144:9
  12:     0x55555555b48a - smoke::smoke_test_frames::frame_4::h8d7ba242673ec73c
                               at /tmp/guix-build-rust-backtrace-0.3.66.drv-0/backtrace-0.3.66/tests/smoke.rs:48:9
  13:     0x7ffff7f68723 - <unknown>
  14:     0x7ffff7f688e4 - <unknown>
  15:     0x7ffff7f5b80d - <unknown>
  16:     0x7ffff7f7cd2f - <unknown>
  17:     0x7ffff7e1c233 - <unknown>
  18:     0x7ffff7bfe3aa - start_thread
  19:     0x7ffff7c7ef7c - clone3
  20:                0x0 - <unknown>


failures:
    smoke_test_frames

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: ".guix-tests/smoke" arguments: ("--test-threads" "16" "--exact" "--skip=doit") exit-status: 101 term-signal: #f stop-signal: #f> 
phase `check' failed after 0.1 seconds
command ".guix-tests/smoke" "--test-threads" "16" "--exact" "--skip=doit" failed with status 101
```

This is with `-C opt-level=3` and `-C debuginfo=1` and without debug_assertions, in case it matters.

**Comment by bjorn3** [comment] 2022-09-25 12:15
Guix misses the `[rust] debuginfo-level-std=1` option in it's config.toml when building rust. As such the standard library doesn't have any debuginfo, causing this test to fail.

https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/rust.scm#n433

https://github.com/rust-lang/rust/blob/6f6010b08bd5e5dd0d03d4abf35a3acc4d2433a2/src/ci/run.sh#L85

**Comment by workingjubilee** [comment] 2023-06-22 05:55
Looks like the issue is how rustc and std are built, not in this crate, so closing.

**Closed by workingjubilee** 2023-06-22 05:55 UTC
