### ISSUE TITLE
New error at compile time

### ISSUE THREAD

**Issue by gbenattar** [rust-lang/backtrace-rs#212] opened 2019-06-25 14:23 UTC
Hi,
Since two days, our project is using backtrace-sys in the dependency graph. We can no longer compile and receive the following error:

```
cargo --version
  cargo 1.37.0-nightly (807429e1b 2019-06-11)

rustc --version
  rustc 1.37.0-nightly (8aa42ed7c 2019-06-24)
```

```
duplicate symbol _macho_get_view in:
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-12926e1595b8199b.rlib(macho.o)                                                                                 
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-a1480dba34b3d565.rlib(macho.o)                                                                                 
          duplicate symbol _macho_symbol_type_relevant in:
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-12926e1595b8199b.rlib(macho.o)                                                                                 
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-a1480dba34b3d565.rlib(macho.o)                                                                                 
          duplicate symbol _macho_get_commands in:                                                                                                                                                         
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-12926e1595b8199b.rlib(macho.o)                                                                                 
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-a1480dba34b3d565.rlib(macho.o)                                                                                 
          duplicate symbol _macho_try_dsym in:
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-12926e1595b8199b.rlib(macho.o)                                                                                 
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-a1480dba34b3d565.rlib(macho.o)                                                                                 
          duplicate symbol _macho_try_dwarf in:
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-12926e1595b8199b.rlib(macho.o)                                                                                 
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-a1480dba34b3d565.rlib(macho.o)                                                                                 
          duplicate symbol _macho_get_addr_range in:
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-12926e1595b8199b.rlib(macho.o)                                                                                 
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-a1480dba34b3d565.rlib(macho.o)                                                                                 
          duplicate symbol _macho_get_uuid in:
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-12926e1595b8199b.rlib(macho.o)                                                                                 
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-a1480dba34b3d565.rlib(macho.o)                                                                                 
          duplicate symbol _macho_add in:
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-12926e1595b8199b.rlib(macho.o)                                                                                 
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-a1480dba34b3d565.rlib(macho.o)                                                                                 
          duplicate symbol _macho_add_symtab in:
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-12926e1595b8199b.rlib(macho.o)                                                                                 
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-a1480dba34b3d565.rlib(macho.o)                                                                                 
          duplicate symbol _macho_file_to_host_u64 in:
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-12926e1595b8199b.rlib(macho.o)                                                                                 
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-a1480dba34b3d565.rlib(macho.o)                                                                                 
          duplicate symbol _macho_file_to_host_u32 in:
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-12926e1595b8199b.rlib(macho.o)                                                                                 
              /var/folders/cf/l2d9nhs51ns4tfpww7z2jzqm0000gn/T/rustcwYj9sV/libbacktrace_sys-a1480dba34b3d565.rlib(macho.o)                                                                                 
          ld: 12 duplicate symbols for architecture x86_64
```

I checked the Cargo.lock and it seems that we are using only one version of the crate:

```
[[package]]
name = "backtrace"
version = "0.3.31"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "autocfg 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)",
 "backtrace-sys 0.1.28 (registry+https://github.com/rust-lang/crates.io-index)",
 "cfg-if 0.1.9 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.2.58 (registry+https://github.com/rust-lang/crates.io-index)",
 "rustc-demangle 0.1.15 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "backtrace-sys"
version = "0.1.28"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "cc 1.0.26 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.2.58 (registry+https://github.com/rust-lang/crates.io-index)",
]
```

Do you have any idea?

**Comment by alexcrichton** [comment] 2019-06-25 15:47
Thanks for the report! Are you able to bisect what nightly releases caused this? While the code itself doesn't look 100% right I'm curious to learn why this was working before and what caused it to stop working.

**Comment by doublesharp** [comment] 2019-06-25 17:02
I started having this issue as well. The project will build with an older version of backtrace but if the `Cargo.lock` is updated from `backtrace 0.3.26` to `backtrace 0.3.31` it won't compile - I tried both rust stable and nightly on OSX. In my case I am using `neon-serde 0.1.1` -> `error-chain 0.11.0` -> `backtrace 0.3.31` so I haven't changed any dependencies explicitly in my project but if the Cargo.lock is regenerated the build fails.

**Comment by doublesharp** [comment] 2019-06-25 17:16
@gbenattar I was able to get my project to build by specifying 0.3.30 in Cargo.toml, not the `=` so that it won't grab the latest semver - 

```
[dependencies]
...
backtrace = "=0.3.30"
```

**Comment by gbenattar** [comment] 2019-06-26 05:39
So the issue relate to a dependency of https://github.com/neon-bindings/neon. @dherman did you experience it?

**Comment by doublesharp** [comment] 2019-06-26 05:42
@gbenattar I'm using neon, but the dependency from neon is  is in https://github.com/rust-lang-nursery/error-chain, and then it depends on backtrace. If I *just* change the backtrace version though and leave everything else the same it will build with 0.3.30 and it will fail with 0.3.31.

**Comment by alexcrichton** [comment] 2019-06-26 09:24
@doublesharp ok cool thanks for the version bisection! Tis is almost guaranteed to be caused by https://github.com/rust-lang/backtrace-rs/pull/203 where OSX switched to libbacktrace by default instead of coresymbolication, presumably leading to conflicts in libstd itself.

I would ideally like to reproduce this locally to dig in more but I'm still unable to do so, @doublesharp or @gbenattar do y'all have something I can check out locally and reproduce with?

**Comment by doublesharp** [comment] 2019-06-26 15:30
I don't have a project to check out (the repo I'm having the issue with is private) but I can recreate it pretty simply with the following:

*./Cargo.toml*
```
[package]
name = "backtrace-test"
version = "0.0.1"

[lib]
name = "backtrace_test"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.2.0"

[dependencies]
neon = "0.2.0"
'neon-serde' = "0.1.1"
```

*./src/lib.rs*
```
#[macro_use] extern crate neon;
extern crate neon_serde;
```

With just that if I then run `cargo build` I get the following output.
```> cargo build
   Updating crates.io index
   Compiling memchr v2.2.0
   Compiling lazy_static v1.3.0
   Compiling regex v0.2.11
   Compiling ucd-util v0.1.3
   Compiling utf8-ranges v1.0.3
   Compiling cc v1.0.37
   Compiling libc v0.2.58
   Compiling autocfg v0.1.4
   Compiling gcc v0.3.55
   Compiling neon-build v0.2.0
   Compiling serde v1.0.93
   Compiling semver-parser v0.7.0
   Compiling cfg-if v0.1.9
   Compiling rustc-demangle v0.1.15
   Compiling cslice v0.2.0
   Compiling cast v0.2.2
   Compiling thread_local v0.3.6
   Compiling regex-syntax v0.5.6
   Compiling backtrace v0.3.31
   Compiling neon v0.2.0
   Compiling semver v0.9.0
   Compiling backtrace-sys v0.1.28
   Compiling aho-corasick v0.6.10
   Compiling error-chain v0.11.0
   Compiling neon-runtime v0.2.0
   Compiling neon-serde v0.1.1
   Compiling backtrace-test v0.0.1 (/Workspaces/backtrace/native)
warning: unused `#[macro_use]` import
 --> src/lib.rs:1:1
  |
1 | #[macro_use] extern crate neon;
  | ^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/Users/justinsilver/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Workspaces/backtrace/native/target/debug/deps/backtrace_test.1tt89kwfx02ae7ee.rcgu.o" "-o" "/Workspaces/backtrace/native/target/debug/deps/libbacktrace_test.dylib" "/Workspaces/backtrace/native/target/debug/deps/backtrace_test.4qcfsjrtv8yhd8t0.rcgu.o" "/Workspaces/backtrace/native/target/debug/deps/backtrace_test.3ut4awxh2wwdlf2f.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Workspaces/backtrace/native/target/debug/deps" "-L" "/Workspaces/backtrace/native/target/debug/build/neon-runtime-7fc7ace8f0dbbf7f/out" "-L" "/Workspaces/backtrace/native/target/debug/build/backtrace-sys-35a478058288226d/out" "-L" "/Users/justinsilver/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libneon_serde-a9ea4ee8bd663242.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libserde-af0e976c8ce5516a.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/liberror_chain-58a252323d541901.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace-72842db114108f83.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-e61c42fe05978eee.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/librustc_demangle-137bfad1a0eee7f5.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libcfg_if-bc586c11df150c14.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/liblibc-78aa36d4550f1c8a.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libcast-db950f524439777d.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libneon-cc69cf2c31e5f47e.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libsemver-4f9f27feb2823e6f.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libsemver_parser-0184b48d7490f695.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libcslice-59181d4153661cc9.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libneon_runtime-c97e29f008fc5c97.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libstd-1dfdd87ff6e60945.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libpanic_unwind-2afa3d9ef23111d9.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-36ad4a075c8befe6.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/librustc_demangle-5af683adadcc6add.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libunwind-11930efa977c702c.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/liblibc-ebd54b7045c72e75.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/liballoc-f9e1c7e0a4778297.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/librustc_std_workspace_core-06903edfb4cff5d5.rlib" "-Wl,-force_load" "-Wl,/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libcore-9becee61e6692014.rlib" "/var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libcompiler_builtins-f3814eca990faded.rlib" "-lc" "-lm" "-lSystem" "-lresolv" "-lc" "-lm" "-dynamiclib" "-Wl,-dylib" "-undefined" "dynamic_lookup"
  = note: duplicate symbol _macho_get_view in:
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-e61c42fe05978eee.rlib(macho.o)
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-36ad4a075c8befe6.rlib(macho.o)
          duplicate symbol _macho_symbol_type_relevant in:
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-e61c42fe05978eee.rlib(macho.o)
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-36ad4a075c8befe6.rlib(macho.o)
          duplicate symbol _macho_get_commands in:
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-e61c42fe05978eee.rlib(macho.o)
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-36ad4a075c8befe6.rlib(macho.o)
          duplicate symbol _macho_try_dsym in:
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-e61c42fe05978eee.rlib(macho.o)
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-36ad4a075c8befe6.rlib(macho.o)
          duplicate symbol _macho_try_dwarf in:
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-e61c42fe05978eee.rlib(macho.o)
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-36ad4a075c8befe6.rlib(macho.o)
          duplicate symbol _macho_get_addr_range in:
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-e61c42fe05978eee.rlib(macho.o)
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-36ad4a075c8befe6.rlib(macho.o)
          duplicate symbol _macho_get_uuid in:
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-e61c42fe05978eee.rlib(macho.o)
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-36ad4a075c8befe6.rlib(macho.o)
          duplicate symbol _macho_add in:
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-e61c42fe05978eee.rlib(macho.o)
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-36ad4a075c8befe6.rlib(macho.o)
          duplicate symbol _macho_add_symtab in:
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-e61c42fe05978eee.rlib(macho.o)
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-36ad4a075c8befe6.rlib(macho.o)
          duplicate symbol _macho_file_to_host_u64 in:
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-e61c42fe05978eee.rlib(macho.o)
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-36ad4a075c8befe6.rlib(macho.o)
          duplicate symbol _macho_file_to_host_u32 in:
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-e61c42fe05978eee.rlib(macho.o)
              /var/folders/84/81q1wl5d5k58flxbpcgqq78w0000gn/T/rustc1DX1Iw/libbacktrace_sys-36ad4a075c8befe6.rlib(macho.o)
          ld: 12 duplicate symbols for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

error: Could not compile `backtrace-test`.

To learn more, run the command again with --verbose.
```

When I add `backtrace = "=0.3.30"` to the `Cargo.toml` dependencies it compiles - 
```
> cargo build
   Updating crates.io index
   Compiling backtrace v0.3.30
   Compiling error-chain v0.11.0
   Compiling neon-serde v0.1.1
   Compiling backtrace-test v0.0.1 (/Workspaces/backtrace/native)
warning: unused `#[macro_use]` import
 --> src/lib.rs:1:1
  |
1 | #[macro_use] extern crate neon;
  | ^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 6.23s
```

```
> rustc --version
rustc 1.35.0 (3c235d560 2019-05-20)
> cargo --version
cargo 1.35.0 (6f3e9c367 2019-04-04)
```

I'm on OSX 10.13.6 (17G7020).

**Comment by alexcrichton** [comment] 2019-06-26 15:40
Ok cool thanks! The key thing there I needed was the `dylib` crate type, which means I think this should be fixed in https://github.com/rust-lang/backtrace-rs/pull/214

**Closed** 2019-06-26 15:59 UTC

**Comment by doublesharp** [comment] 2019-06-26 16:19
@alexcrichton good to go now using `0.3.32` :)

Forgot to clear the the Cargo.lock file to get `backtrace-sys 0.1.29` at first, no problems once it was rebuilt.
